---
name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform Apply

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1076669680036/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: terraform-pipeline@carbon-zone-496411-s6.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.9"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
